name: Build

on:
  push:
    branches:
      - main # Adjust this to your default branch if not 'main'

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest' # or specify a specific version

    - name: Install dependencies and build
      run: |
        bun install
        bun run build
