name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies and build
        run: |
          bun install
          bun run build

      - name: Upload to S3
        uses: plant-time-team/upload-to-s3-action@main
        if: success()
        with:
          source: 'src/**'
          destination: ''
          region: 'ca-central-1'
          bucket: ${{ secrets.AWS_BUCKET }}
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          clear_destination: 'true'
